spring:
  application:
    name: retryer

server:
  servlet:
    context-path: /retryer

logging:
  level:
    root: info
    org.springframework.boot.web.servlet: trace
    com.github.cyberpunkperson: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X] %logger{80} %msg%n'

kafka:
  config:
    default: &default-kafka-config
      bootstrap-servers: localhost:29092
      properties:
        request.timeout.ms: 300000
      producer: &default-producer
        properties:
          acks: all
      consumer: &default-consumer
        group-id: ${spring.application.name}
        properties:
          max.poll.records: 50
          max.poll.interval.ms: 500000
          session.timeout.ms: 60000
          auto.offset.reset: latest
  topic:
    source:
      name: ${spring.application.name}.source
      <<: *default-kafka-config
      consumer:
        enable-auto-commit: false
        <<: *default-consumer
      listener.concurrency: 3
    router:
      <<: *default-kafka-config
      consumer:
        enable-auto-commit: false
        <<: *default-consumer
      listener.concurrency: 3
      producer: *default-producer

router:
  queue:
    delays:
      PT5M: &5M
        duration: PT5M
        topic: ${spring.application.name}.delay.${router.queue.delays.PT5M.duration}
      PT30M: &30M
        duration: PT30M
        topic: ${spring.application.name}.delay.${router.queue.delays.PT30M.duration}
      PT1H: &1H
        duration: PT1H
        topic: ${spring.application.name}.delay.${router.queue.delays.PT1H.duration}
    flows:
      default:
        - *5M
        - *5M
        - *30M
        - *1H

archive:
  topic: ${spring.application.name}.archive #todo DLT?