spring:
  application:
    name: retryer

server:
  servlet:
    context-path: /retryer

logging:
  level:
    root: info
    org.springframework.boot.web.servlet: trace
    com.github.cyberpunkperson: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X] %logger{80} %msg%n'

kafka:
  config:
    default: &default-kafka-config
      bootstrap-servers: kafka:9092
      properties:
        request.timeout.ms: 300000
      producer: &default-producer
        properties:
          acks: all
      consumer: &default-consumer
        group-id: ${spring.application.name}
        enable-auto-commit: false
        properties:
          max.poll.records: 50
          max.poll.interval.ms: 500000
          session.timeout.ms: 60000
          auto.offset.reset: latest
  topic:
    entry:
      name: ${spring.application.name}.entry
      <<: *default-kafka-config
      consumer:
        <<: *default-consumer
      listener.concurrency: 3
    queue:
      <<: *default-kafka-config
      consumer:
        <<: *default-consumer
      listener.concurrency: 3
    exit:
      <<: *default-kafka-config
      producer: *default-producer


queue:
  delays:
    PT5M: &5M
      duration: PT5M
      topic: ${spring.application.name}.delay.${queue.delays.PT5M.duration}
    PT30M: &30M
      duration: PT30M
      topic: ${spring.application.name}.delay.${queue.delays.PT30M.duration}
    PT1H: &1H
      duration: PT1H
      topic: ${spring.application.name}.delay.${queue.delays.PT1H.duration}
  backoffs:
    default:
      - *5M
      - *5M
      - *30M
      - *1H

archive:
  topic: ${spring.application.name}.archive